workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    environment:
      flutter: stable
      xcode: latest
      groups:
        - namecard_secrets
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files com.hirokino.namecardapp \
            --type IOS_APP_STORE \
            --create
          app-store-connect create-certificate \
            --type IOS_DISTRIBUTION
          keychain add-certificates
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          echo "API KEY LENGTH: ${#GOOGLE_VISION_API_KEY}"
          flutter build ipa \
            --release \
            --dart-define=GOOGLE_VISION_API_KEY=$GOOGLE_VISION_API_KEY
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
